export default [
    {
      id: 41,
      price: "3.6$",
      category: "pasta",
      brand: "Bertolli",
      rating: "4.6",
      availability: "yes",
      image: "https://example.com/images/bertolli_pasta.jpg",
    },
    {
      id: 42,
      price: "3.1$",
      category: "snacks",
      brand: "Kirkland",
      rating: "4.3",
      availability: "yes",
      image: "https://example.com/images/kirkland_snacks.jpg",
    },
    {
      id: 43,
      price: "2.4$",
      category: "canned",
      brand: "Libby's",
      rating: "4.0",
      availability: "yes",
      image: "https://example.com/images/libbys_canned.jpg",
    },
    {
      id: 44,
      price: "4.6$",
      category: "beverages",
      brand: "Monster",
      rating: "4.7",
      availability: "yes",
      image: "https://example.com/images/monster_beverages.jpg",
    },
    {
      id: 45,
      price: "2.3$",
      category: "frozen",
      brand: "Healthy Choice",
      rating: "4.4",
      availability: "yes",
      image: "https://example.com/images/healthy_choice_frozen.jpg",
    },
    {
      id: 46,
      price: "3.3$",
      category: "spices",
      brand: "Badia",
      rating: "4.8",
      availability: "yes",
      image: "https://example.com/images/badia_spices.jpg",
    },
    {
      id: 47,
      price: "2.6$",
      category: "cookies",
      brand: "Little Debbie",
      rating: "4.1",
      availability: "yes",
      image: "https://example.com/images/little_debbie_cookies.jpg",
    },
    {
      id: 48,
      price: "3.7$",
      category: "yogurt",
      brand: "Dannon",
      rating: "4.7",
      availability: "no",
      image: "https://example.com/images/dannon_yogurt.jpg",
    },
    {
      id: 49,
      price: "4.4$",
      category: "cheese",
      brand: "President",
      rating: "4.6",
      availability: "yes",
      image: "https://example.com/images/president_cheese.jpg",
    },
    {
      id: 50,
      price: "5.6$",
      category: "coffee",
      brand: "McCafe",
      rating: "4.7",
      availability: "yes",
      image: "https://example.com/images/mccafe_coffee.jpg",
    }
];
