export default [
    {
      id: 11,
      price: "3.8$",
      category: "pasta",
      brand: "Ronzoni",
      rating: "4.5",
      availability: "yes",
      image: "https://example.com/images/ronzoni_pasta.jpg",
    },
    {
      id: 12,
      price: "3.0$",
      category: "snacks",
      brand: "Snyder's",
      rating: "4.2",
      availability: "yes",
      image: "https://example.com/images/snyders_snacks.jpg",
    },
    {
      id: 13,
      price: "2.1$",
      category: "canned",
      brand: "Campbell's",
      rating: "4.1",
      availability: "yes",
      image: "https://example.com/images/campbells_canned.jpg",
    },
    {
      id: 14,
      price: "4.5$",
      category: "beverages",
      brand: "Powerade",
      rating: "4.6",
      availability: "yes",
      image: "https://example.com/images/powerade_beverages.jpg",
    },
    {
      id: 15,
      price: "2.2$",
      category: "frozen",
      brand: "Lean Cuisine",
      rating: "4.3",
      availability: "yes",
      image: "https://example.com/images/lean_cuisine_frozen.jpg",
    },
    {
      id: 16,
      price: "3.2$",
      category: "spices",
      brand: "McCormick",
      rating: "4.8",
      availability: "yes",
      image: "https://example.com/images/mccormick_spices.jpg",
    },
    {
      id: 17,
      price: "2.5$",
      category: "cookies",
      brand: "Otis Spunkmeyer",
      rating: "4.2",
      availability: "yes",
      image: "https://example.com/images/otis_cookies.jpg",
    },
    {
      id: 18,
      price: "3.8$",
      category: "yogurt",
      brand: "Chobani",
      rating: "4.7",
      availability: "no",
      image: "https://example.com/images/chobani_yogurt.jpg",
    },
    {
      id: 19,
      price: "4.2$",
      category: "cheese",
      brand: "Kraft",
      rating: "4.5",
      availability: "yes",
    },
    {
      id: 20,
      price: "5.2$",
      category: "coffee",
      brand: "Starbucks",
      rating: "4.6",
      availability: "yes",
      image: "https://example.com/images/starbucks_coffee.jpg",
    }
];
