export default [
    {
      id: 51,
      price: "4.1$",
      category: "pasta",
      brand: "Colavita",
      rating: "4.5",
      availability: "yes",
      image: "https://example.com/images/colavita_pasta.jpg",
    },
    {
      id: 52,
      price: "3.4$",
      category: "snacks",
      brand: "Cape Cod",
      rating: "4.3",
      availability: "yes",
      image: "https://example.com/images/cape_cod_snacks.jpg",
    },
    {
      id: 53,
      price: "2.6$",
      category: "canned",
      brand: "Bush's",
      rating: "4.2",
      availability: "yes",
      image: "https://example.com/images/bushs_canned.jpg",
    },
    {
      id: 54,
      price: "4.7$",
      category: "beverages",
      brand: "Red Bull",
      rating: "4.8",
      availability: "yes",
      image: "https://example.com/images/red_bull_beverages.jpg",
    },
    {
      id: 55,
      price: "2.4$",
      category: "frozen",
      brand: "Marie Callender's",
      rating: "4.3",
      availability: "yes",
      image: "https://example.com/images/marie_callenders_frozen.jpg",
    },
    {
      id: 56,
      price: "3.5$",
      category: "spices",
      brand: "Simply Organic",
      rating: "4.9",
      availability: "yes",
      image: "https://example.com/images/simply_organic_spices.jpg",
    },
    {
      id: 57,
      price: "2.9$",
      category: "cookies",
      brand: "Entenmann's",
      rating: "4.4",
      availability: "yes",
      image: "https://example.com/images/entenmanns_cookies.jpg",
    },
    {
      id: 58,
      price: "3.8$",
      category: "yogurt",
      brand: "Stonyfield",
      rating: "4.6",
      availability: "no",
      image: "https://example.com/images/stonyfield_yogurt.jpg",
    },
    {
      id: 59,
      price: "4.5$",
      category: "cheese",
      brand: "Horizon",
      rating: "4.8",
      availability: "yes",
      image: "https://example.com/images/horizon_cheese.jpg",
    },
    {
      id: 60,
      price: "5.7$",
      category: "coffee",
      brand: "Caribou Coffee",
      rating: "4.6",
      availability: "yes",
      image: "https://example.com/images/caribou_coffee.jpg",
    }
];
