export default [
    {
      id: 31,
      price: "4.0$",
      category: "pasta",
      brand: "Barilla",
      rating: "4.7",
      availability: "yes",
      image: "https://example.com/images/barilla_pasta.jpg",
    },
    {
      id: 32,
      price: "3.2$",
      category: "snacks",
      brand: "Pringles",
      rating: "4.4",
      availability: "yes",
      image: "https://example.com/images/pringles_snacks.jpg",
    },
    {
      id: 33,
      price: "2.3$",
      category: "canned",
      brand: "Progresso",
      rating: "4.1",
      availability: "yes",
      image: "https://example.com/images/progresso_canned.jpg",
    },
    {
      id: 34,
      price: "4.4$",
      category: "beverages",
      brand: "Arizona",
      rating: "4.6",
      availability: "yes",
      image: "https://example.com/images/arizona_beverages.jpg",
    },
    {
      id: 35,
      price: "2.5$",
      category: "frozen",
      brand: "Stouffer's",
      rating: "4.2",
      availability: "yes",
      image: "https://example.com/images/stouffers_frozen.jpg",
    },
    {
      id: 36,
      price: "3.4$",
      category: "spices",
      brand: "Lawry's",
      rating: "4.7",
      availability: "yes",
      image: "https://example.com/images/lawrys_spices.jpg",
    },
    {
      id: 37,
      price: "2.8$",
      category: "cookies",
      brand: "Famous Amos",
      rating: "4.2",
      availability: "yes",
      image: "https://example.com/images/famous_amos_cookies.jpg",
    },
    {
      id: 38,
      price: "3.9$",
      category: "yogurt",
      brand: "Yoplait",
      rating: "4.6",
      availability: "no",
      image: "https://example.com/images/yoplait_yogurt.jpg",
    },
    {
      id: 39,
      price: "4.3$",
      category: "cheese",
      brand: "Cabot",
      rating: "4.7",
      availability: "yes",
      image: "https://example.com/images/cabot_cheese.jpg",
    },
    {
      id: 40,
      price: "5.5$",
      category: "coffee",
      brand: "Dunkin'",
      rating: "4.6",
      availability: "yes",
      image: "https://example.com/images/dunkin_coffee.jpg",
    }
];
