export default [
    {
      id: 21,
      price: "3.7$",
      category: "pasta",
      brand: "De Cecco",
      rating: "4.4",
      availability: "yes",
      image: "https://example.com/images/dececco_pasta.jpg",
    },
    {
      id: 22,
      price: "2.9$",
      category: "snacks",
      brand: "Goldfish",
      rating: "4.1",
      availability: "yes",
      image: "https://example.com/images/goldfish_snacks.jpg",
    },
    {
      id: 23,
      price: "2.0$",
      category: "canned",
      brand: "Hunt's",
      rating: "4.2",
      availability: "yes",
      image: "https://example.com/images/hunts_canned.jpg",
    },
    {
      id: 24,
      price: "4.3$",
      category: "beverages",
      brand: "Vitaminwater",
      rating: "4.5",
      availability: "yes",
      image: "https://example.com/images/vitaminwater_beverages.jpg",
    },
    {
      id: 25,
      price: "2.1$",
      category: "frozen",
      brand: "Birds Eye",
      rating: "4.3",
      availability: "yes",
      image: "https://example.com/images/birds_eye_frozen.jpg",
    },
    {
      id: 26,
      price: "3.1$",
      category: "spices",
      brand: "Spice Islands",
      rating: "4.6",
      availability: "yes",
      image: "https://example.com/images/spice_islands_spices.jpg",
    },
    {
      id: 27,
      price: "2.4$",
      category: "cookies",
      brand: "Keebler",
      rating: "4.3",
      availability: "yes",
      image: "https://example.com/images/keebler_cookies.jpg",
    },
    {
      id: 28,
      price: "3.6$",
      category: "yogurt",
      brand: "Oikos",
      rating: "4.8",
      availability: "no",
      image: "https://example.com/images/oikos_yogurt.jpg",
    },
    {
      id: 29,
      price: "4.1$",
      category: "cheese",
      brand: "Sargento",
      rating: "4.7",
      availability: "yes",
      image: "https://example.com/images/sargento_cheese.jpg",
    },
    {
      id: 30,
      price: "5.3$",
      category: "coffee",
      brand: "Peet's Coffee",
      rating: "4.5",
      availability: "yes",
      image: "https://example.com/images/peets_coffee.jpg",
    }
];
